version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      jfoundry-maven-libraries:
        patterns: ["*"]
        exclude-patterns:
          - org.apache.maven.plugins:maven-compiler-plugin
          - org.apache.maven.plugins:maven-source-plugin
          - org.graalvm.buildtools:native-maven-plugin
        update-types: [patch, minor, major]
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
      - dependency-name: org.springframework.cloud:spring-cloud-dependencies
      - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      github-codeql-action:
        patterns: [github/codeql-action/*]
