<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.xfoundries</groupId>
        <artifactId>jfoundry-parent</artifactId>
        <version>1.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>jfoundry-starters</artifactId>
    <packaging>pom</packaging>
    <name>jfoundry-starters</name>
    <description>Runtime-neutral dependency starters for jfoundry core capabilities.</description>

    <modules>
        <module>jfoundry-domain-starter</module>
        <module>jfoundry-application-starter</module>
        <module>infrastructure/jfoundry-persistence-mybatis-plus-starter</module>
        <module>infrastructure/jfoundry-persistence-jpa-starter</module>
    </modules>
</project>
