<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.xfoundries</groupId>
        <artifactId>jfoundry-spring</artifactId>
        <version>1.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>jfoundry-spring-integration-tests</artifactId>
    <name>jfoundry-spring-integration-tests</name>
    <description>Spring runtime integration verification.</description>

    <dependencies>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-architecture-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-domain</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-transaction-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-domain-event-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-domain-event-externalization-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-inbox-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-messaging-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-persistence-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-persistence-mybatis-plus</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-messaging-jackson</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-mybatis-plus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-inbox-mybatis-plus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-jpa</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-inbox-jpa</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-jobrunr</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-domain-event-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-messaging-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-transaction-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-webmvc-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-messaging-spring-boot-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-inbox-spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.xfoundries</groupId>
            <artifactId>jfoundry-outbox-spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmolecules.integrations</groupId>
            <artifactId>jmolecules-jackson3</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmolecules.integrations</groupId>
            <artifactId>jmolecules-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>kafka</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>rabbitmq</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.amqp</groupId>
            <artifactId>spring-rabbit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-empty-javadoc</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classesDirectory>${maven.multiModuleProjectDirectory}/.mvn/javadoc-placeholder</classesDirectory>
                            <classifier>javadoc</classifier>
                            <includes>
                                <include>README.md</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/*IT.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>4.1.0</version>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>1.1.9</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.shared</groupId>
                        <artifactId>maven-shared-utils</artifactId>
                        <version>3.4.2</version>
                    </dependency>
                </dependencies>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>it</id>
            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-jdbc</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/*IT.java</include>
                            </includes>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>process-aot</id>
                                <goals>
                                    <goal>process-aot</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <configuration>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-reachability-metadata</id>
                                <goals>
                                    <goal>add-reachability-metadata</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>build-native-image</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>native-mybatis-plus</id>
            <dependencies>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-domain</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-transaction-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-domain-event-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-domain-event-externalization-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-messaging-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-messaging-jackson</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-domain-event-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-messaging-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-transaction-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-persistence-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-persistence-mybatis-plus</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-persistence-mybatis-plus-spring-boot-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-mybatis-plus-spring-boot-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-inbox-mybatis-plus-spring-boot-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.baomidou</groupId>
                    <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.baomidou</groupId>
                    <artifactId>mybatis-plus-jsqlparser</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.baomidou</groupId>
                    <artifactId>mybatis-plus-spring-boot-native-image</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>add-native-mybatis-plus-source</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>add-source</goal>
                                </goals>
                                <configuration>
                                    <sources>
                                        <source>src/native-mybatis-plus/java</source>
                                    </sources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>add-native-mybatis-plus-test-source</id>
                                <phase>generate-test-sources</phase>
                                <goals>
                                    <goal>add-test-source</goal>
                                </goals>
                                <configuration>
                                    <sources>
                                        <source>src/native-mybatis-plus-test/java</source>
                                    </sources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/NativeMybatisPlusIT.java</include>
                            </includes>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>org.jfoundry.integration.nativeimage.mybatisplus.NativeMybatisPlusApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <id>process-aot-mybatis-plus</id>
                                <goals>
                                    <goal>process-aot</goal>
                                </goals>
                                <configuration>
                                    <arguments>
                                        <argument>--spring.datasource.url=jdbc:postgresql://localhost:5432/jfoundry</argument>
                                        <argument>--spring.datasource.username=jfoundry</argument>
                                        <argument>--spring.datasource.password=jfoundry</argument>
                                        <argument>--spring.datasource.driver-class-name=org.postgresql.Driver</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <configuration>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <imageName>jfoundry-spring-mybatis-plus-native</imageName>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-mybatis-plus-reachability-metadata</id>
                                <goals>
                                    <goal>add-reachability-metadata</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>build-mybatis-plus-native-image</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>native-redisson</id>
            <dependencies>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-lock-redisson-spring-boot-starter</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>add-native-redisson-source</id>
                                <phase>generate-sources</phase>
                                <goals><goal>add-source</goal></goals>
                                <configuration>
                                    <sources><source>src/native-redisson/java</source></sources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>add-native-redisson-test-source</id>
                                <phase>generate-test-sources</phase>
                                <goals><goal>add-test-source</goal></goals>
                                <configuration>
                                    <sources><source>src/native-redisson-test/java</source></sources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <includes><include>**/NativeRedissonLockIT.java</include></includes>
                        </configuration>
                        <executions>
                            <execution>
                                <goals><goal>integration-test</goal><goal>verify</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>org.jfoundry.integration.nativeimage.redisson.NativeRedissonLockApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <id>process-aot-redisson</id>
                                <goals><goal>process-aot</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <configuration>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <imageName>jfoundry-spring-redisson-native</imageName>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-redisson-reachability-metadata</id>
                                <goals><goal>add-reachability-metadata</goal></goals>
                            </execution>
                            <execution>
                                <id>build-redisson-native-image</id>
                                <goals><goal>compile-no-fork</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>native-jobrunr</id>
            <dependencies>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-messaging-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-transaction-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-transaction-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-messaging-jackson</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-domain-event-externalization-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-jpa</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-jobrunr</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-spring</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-spring-boot-autoconfigure</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-jobrunr-spring-boot-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>io.github.xfoundries</groupId>
                    <artifactId>jfoundry-outbox-jpa-spring-boot-starter</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-data-jpa</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>add-native-jobrunr-source</id>
                                <phase>generate-sources</phase>
                                <goals><goal>add-source</goal></goals>
                                <configuration>
                                    <sources><source>src/native-jobrunr/java</source></sources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>add-native-jobrunr-test-source</id>
                                <phase>generate-test-sources</phase>
                                <goals><goal>add-test-source</goal></goals>
                                <configuration>
                                    <sources><source>src/native-jobrunr-test/java</source></sources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <includes><include>**/NativeJobRunrIT.java</include></includes>
                        </configuration>
                        <executions>
                            <execution>
                                <goals><goal>integration-test</goal><goal>verify</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>org.jfoundry.integration.nativeimage.jobrunr.NativeJobRunrApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <id>process-aot-jobrunr</id>
                                <goals><goal>process-aot</goal></goals>
                                <configuration>
                                    <arguments>
                                        <argument>--jfoundry.outbox.dispatcher.mode=jobrunr</argument>
                                        <argument>--jobrunr.background-job-server.enabled=true</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <configuration>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <imageName>jfoundry-spring-jobrunr-native</imageName>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-jobrunr-reachability-metadata</id>
                                <goals><goal>add-reachability-metadata</goal></goals>
                            </execution>
                            <execution>
                                <id>build-jobrunr-native-image</id>
                                <goals><goal>compile-no-fork</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
